language: objective-c
before_script:
    - brew update && brew upgrade xctool
script:
    - xctool test -project STPopupPreviewExample/STPopupPreviewExample.xcodeproj -scheme STPopupPreviewExample -sdk iphonesimulator
